#pragma once

#ifndef _AR_LOG_CHANNELS_
#define _AR_LOG_CHANNELS_

#include "Logging/LogMacros.h"

ARRANGER_API DECLARE_LOG_CATEGORY_EXTERN(LogARPhysics, Log, All);
ARRANGER_API DECLARE_LOG_CATEGORY_EXTERN(LogARRepository, Log, All);
ARRANGER_API DECLARE_LOG_CATEGORY_EXTERN(LogAREditorAsset, Log, All);
ARRANGER_API DECLARE_LOG_CATEGORY_EXTERN(LogARBattle, Log, All);

#endif // _AR_LOG_CHANNELS_